spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc连接url
    password: 你的数据库密码
    username: 你的数据库用户名
    hikari:
      max-lifetime: 500000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: select 1
  redis:
    database: 5
    host: 你的redis地址
    port: 6379
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 8483